apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cs720

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - backend-deployment.yaml
  - proxy-deployment.yaml
  - ai-service-deployment.yaml
  - frontend-deployment.yaml
  - hpa.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: cs720-platform
  app.kubernetes.io/managed-by: flux

images:
  - name: ghcr.io/OWNER/cs720-backend
    newTag: latest
  - name: ghcr.io/OWNER/cs720-proxy
    newTag: latest
  - name: ghcr.io/OWNER/cs720-ai-service
    newTag: latest
  - name: ghcr.io/OWNER/cs720-frontend
    newTag: latest
